[build]
command = "yarn build:prod"
publish = "dist/client"

[build.environment]
NODE_VERSION = "20"
YARN_VERSION = "1.22.19"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*.js"
to = "/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; connect-src 'self' *.netlify.app; img-src 'self' data: blob: *.netlify.app; style-src 'self' 'unsafe-inline'; font-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.netlify.app; frame-src 'self' app.netlify.com *.netlify.app; worker-src 'self' blob:;"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/assets/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css"

[[headers]]
for = "/assets/*.css"
[headers.values]
Content-Type = "text/css"

[[headers]]
for = "/assets/*.woff2"
[headers.values]
Content-Type = "font/woff2"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.woff"
[headers.values]
Content-Type = "font/woff"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.ttf"
[headers.values]
Content-Type = "font/ttf"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
