name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build App
        run: one build

      - name: Build Storybook
        env:
          STORYBOOK_BASE_URL: /storybook/
        run: NODE_ENV=production storybook build

      - name: Debug build output
        run: |
          echo "=== App Build Output ==="
          ls -la dist/client/ || echo "Failed to list dist/client/"
          echo "=== App Build Assets ==="
          ls -la dist/client/assets/ || echo "Failed to list assets/"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Debug Storybook build
        continue-on-error: true
        run: |
          echo "=== Storybook Static Directory Structure ==="
          tree storybook-static || ls -R storybook-static
          echo "=== Storybook index.html ==="
          cat storybook-static/index.html
          echo "=== Storybook iframe.html ==="
          cat storybook-static/iframe.html

      - name: Copy Storybook to dist
        run: |
          # First remove any existing storybook directory
          rm -rf dist/client/storybook
          # Create fresh directory and copy files
          mkdir -p dist/client/storybook
          cp -r storybook-static/* dist/client/storybook/
          # Verify the copy
          echo "=== Verifying Storybook copy ==="
          tree dist/client/storybook || ls -R dist/client/storybook
          echo "=== Checking asset references ==="
          grep -r "assets/" dist/client/storybook/
          echo "=== Checking HTML files ==="
          find dist/client/storybook -name "*.html" -type f -exec echo {} \; -exec cat {} \;

      - name: Debug final structure
        continue-on-error: true
        run: |
          echo "=== Final Dist Structure (limited) ==="
          ls -R dist/client/ | head -n 50 || echo "Failed to list structure"
          echo "=== Final Storybook Assets ==="
          ls -la dist/client/storybook/assets/ || echo "Failed to list final assets"
          echo "=== Final Storybook HTML (first 50 lines) ==="
          head -n 50 dist/client/storybook/index.html || echo "Failed to read final index.html"
          echo "=== Check Final Asset Paths (limited) ==="
          grep -r "/storybook/" dist/client/storybook/ | head -n 20 || echo "No final references found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/client'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
