name: PR Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build
        run: yarn build:prod
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-preview-${{ github.event.pull_request.number }}
          path: './dist/client'
          retention-days: 7 